# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

#volumes:
#  orderer2.example.com:

services:
  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com

  orderer2.example.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer2.example.com
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer2.example.com:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.example.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer3.example.com
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/:/var/hyperledger/orderer/tls
    ports:
    - 9050:7050

#  orderer4.example.com:
#    extends:
#      file: base/peer-base.yaml
#      service: orderer-base
#    container_name: orderer4.example.com
#    volumes:
#        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
#        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/msp:/var/hyperledger/orderer/msp
#        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/tls/:/var/hyperledger/orderer/tls
#    ports:
#    - 10050:7050
#
#  orderer5.example.com:
#    extends:
#      file: base/peer-base.yaml
#      service: orderer-base
#    container_name: orderer5.example.com
#    volumes:
#        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
#        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/msp:/var/hyperledger/orderer/msp
#        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/tls/:/var/hyperledger/orderer/tls
#    ports:
#    - 11050:7050

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.example.com

#  peer1.org1.example.com:
#    container_name: peer1.org1.example.com
#    extends:
#      file:  base/docker-compose-base.yaml
#      service: peer1.org1.example.com
#
#  peer0.org2.example.com:
#    container_name: peer0.org2.example.com
#    extends:
#      file:  base/docker-compose-base.yaml
#      service: peer0.org2.example.com
#
#  peer1.org2.example.com:
#    container_name: peer1.org2.example.com
#    extends:
#      file:  base/docker-compose-base.yaml
#      service: peer1.org2.example.com
